listener 8883
cafile /mosquitto/config/tls/ca.pem
certfile /mosquitto/config/tls/server.pem
keyfile /mosquitto/config/tls/server.key
allow_anonymous true

plugin /mosquitto/plugins/libmosquitto_auth_biscuit.so
plugin_opt_jwt_alg ES256
plugin_opt_jwt_key_file /mosquitto/config/jwt_public.pem
plugin_opt_biscuit_root_key_file /mosquitto/config/biscuit_public.key

plugin_opt_policy_mode dynamic_security
plugin_opt_dynamic_security_url /mosquitto/config/dynamic-security-anon.json
plugin_opt_dynamic_security_reload_interval_seconds 1
plugin_opt_cache_ttl_seconds 3600
plugin_opt_allow_anonymous_no_token true
plugin_opt_ext_auth_method token

log_dest stderr
log_type all
