[workspace]
members = [
  "crates/mosquitto-plugin",
  "crates/token-issuer",
  "crates/benchmarks",
  "crates/authz-server",
]
resolver = "2"

[profile.release]
panic = "abort"
strip = true
lto = true
codegen-units = 1
opt-level = "z"
overflow-checks = false

[profile.release-maxperf]
inherits = "release"
panic = "abort"
strip = true
lto = "fat"
codegen-units = 1
overflow-checks = false

[workspace.lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(kani)'] }
