/* Generated by cbindgen */

#ifndef MOSQUITTO_AUTH_BISCUIT_H
#define MOSQUITTO_AUTH_BISCUIT_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#define MOSQ_ERR_SUCCESS 0

#define MOSQ_ERR_NOMEM 1

#define MOSQ_ERR_INVAL 3

#define MOSQ_ERR_AUTH 11

#define MOSQ_ERR_ACL_DENIED 12

#define MOSQ_ERR_PLUGIN_DEFER 17

#define MOSQ_EVT_ACL_CHECK 2

#define MOSQ_EVT_BASIC_AUTH 3

#define MOSQ_LOG_INFO (1 << 0)

#define MOSQ_LOG_ERR (1 << 3)

typedef struct MosquittoPluginId {
  uint8_t _unused[0];
} MosquittoPluginId;

typedef int (*MosqFuncGenericCallback)(int, void*, void*);

typedef struct MosquittoOpt {
  char *key;
  char *value;
} MosquittoOpt;

extern int mosquitto_callback_register(struct MosquittoPluginId *identifier,
                                       int event,
                                       MosqFuncGenericCallback cb_func,
                                       const void *event_data,
                                       void *userdata);

extern void mosquitto_log_printf(int level, const char *fmt, ...);

extern const char *mosquitto_client_id(const void *client);

int mosquitto_plugin_version(int _supported_version_count, const int *_supported_versions);

int mosquitto_plugin_init(struct MosquittoPluginId *identifier,
                          void **userdata,
                          struct MosquittoOpt *_options,
                          int _option_count);

int mosquitto_plugin_cleanup(void *_userdata, struct MosquittoOpt *_options, int _option_count);

#endif  /* MOSQUITTO_AUTH_BISCUIT_H */
