FROM eclipse-mosquitto:2.0.15
# Install dependencies from local context
COPY docker/packages/*.apk /tmp/
RUN apk add --allow-untrusted /tmp/*.apk && \
    rm /tmp/*.apk

COPY target/release/libmosquitto_auth_biscuit.so /mosquitto/plugins/
# mosquitto.conf is already mounted via docker-compose
