FROM debian:bookworm-slim

RUN apt-get update && apt-get install -y --no-install-recommends iproute2 \
    && rm -rf /var/lib/apt/lists/*

COPY docker/netem_entrypoint.sh /netem_entrypoint.sh
RUN chmod +x /netem_entrypoint.sh

ENTRYPOINT ["/netem_entrypoint.sh"]
