listener 1883
allow_anonymous false

plugin /mosquitto/plugins/libmosquitto_auth_biscuit.so
plugin_opt_jwt_alg ES256
plugin_opt_jwt_key_file /mosquitto/config/jwt_public.pem
plugin_opt_biscuit_root_key_file /mosquitto/config/biscuit_public.key
plugin_opt_biscuit_authorizer_profile contextual

plugin_opt_policy_mode token
plugin_opt_cache_ttl_seconds 3600
plugin_opt_ext_auth_method token

log_dest stderr
log_type all
