listener 1883
allow_anonymous false

plugin /mosquitto/plugins/libmosquitto_auth_biscuit.so
# plugin_opt_jwt_key /mosquitto/config/jwt_pub.pem
# plugin_opt_biscuit_key /mosquitto/config/biscuit_pub.key

log_dest stderr
log_type all
