global:
  scrape_interval: 5s
scrape_configs:
  - job_name: "mosquitto"
    static_configs:
      - targets: [
          "mosquitto:1883",
        ] # Mosquitto doesn't expose prometheus natively easily without exporter
