[build]
rustflags = ["-C", "target-cpu=native"]

[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "target-cpu=native", "-C", "target-feature=+aes,+sse2,+sse4.1,+avx2"]

[profile.release]
debug = false
debug-assertions = false
