name: Miri

on:
  push:
    paths:
      - "mqtt-auth-biscuit/**"
      - ".github/workflows/miri.yml"
      - "rust-toolchain.toml"
  pull_request:
    paths:
      - "mqtt-auth-biscuit/**"
      - ".github/workflows/miri.yml"
      - "rust-toolchain.toml"

jobs:
  miri:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Install nightly Rust with Miri
        uses: dtolnay/rust-toolchain@e97e2d8cc328f1b50210efc529dca0028893a2d9
        with:
          toolchain: nightly-2026-03-20
          components: miri

      - name: Miri setup
        run: cargo --config build.rustflags=[] miri setup -p mosquitto-auth-biscuit
        working-directory: mqtt-auth-biscuit

      - name: Run Miri tests
        run: cargo --config build.rustflags=[] miri test -p mosquitto-auth-biscuit
        working-directory: mqtt-auth-biscuit
        env:
          MIRIFLAGS: -Zmiri-disable-isolation
